### ISSUE TITLE
make example footnote in Rmarkdown style?

### ISSUE THREAD

**Issue by derekpowell** [kemacdonald/cogsci2016#3]
Kyle - this template is **AWESOME**. You are the man.

I had one suggestion tho: you might use rmarkdown-style footnotes in the template to guide users as to best practice. Using the latex footnote behaves strangely sometimes: e.g., it seems to eat quotation marks and of course it won't respect markdown syntax. Only catch I see is github-flavored markdown doesn't support footnotes, so I guess it's not 100% supported as part of markdown itself

```
In case you're not familiar, markdown footnotes look like this [^1]

[^1]: wrote this as a code block so you can see the raw text
```

I just tested this in one of my cogsci papers and everything works perfectly as expected

**Comment by kemacdonald** [comment]
Done! Thanks for the suggestion.
