### ISSUE TITLE
trouble compiling (post-Catalina update? -- but also on Windows...)

### ISSUE THREAD

**Issue by kachergis** [kemacdonald/cogsci2016#7]
I'm running into a problem compiling even an empty template, on both macOS and Windows...

Updated TinyTex and tried to track down all missing latex packages, but still getting an error: "! LaTeX Error: This NFSS system isn't set up properly." and in the log: "No file OMSpzccm.fd."

more from the log:
```
LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 62.
LaTeX Font Info:    ... okay on input line 62.
LaTeX Font Info:    Checking defaults for OMS/pzccm/m/n on input line 62.
LaTeX Font Info:    Trying to load font information for OMS+pzccm on input line
 62.
No file OMSpzccm.fd.
```

**Comment by mllewis** [comment]
You've probably figured this out by now - but installing this package seems to solve the problem:

https://ctan.org/tex-archive/macros/latex/required/psnfss?lang=en

**Comment by kachergis** [comment]
thanks! installed in R with 
`tinytex::tlmgr_install("psnfss")`
and now works
