### ISSUE TITLE
Template throws error: "! LaTeX Error: Environment CSLReferences undefined."

### ISSUE THREAD

**Issue by CharlotteMoore927** [kemacdonald/cogsci2016#8]
I'm having an issue where if I try to knit the template as-is without making any of my own changes, I get the above error. I think the last commit on this repo was to stop this from happening but it's still happening for me. I'm running R vers. 4.0.3 on Catalina.

**Comment by dyurovsky** [comment]
Hi, @CharlotteMoore927, I just fixed this in a new pull request. If you see this before Kyle has a chance to look look at the request, you can use the template from my fork here
https://github.com/dyurovsky/cogsci2016

You'll need to use devtools::install_github("dyurovsky/cogsci2016")

**Comment by CharlotteMoore927** [comment]
Hi Dan, This worked! Thanks very much

**Comment by kemacdonald** [comment]
thanks for the fix @dyurovsky! closing this out
